version: '2'
services:
  shipRouteApi:
    image: 'registry.cn-hangzhou.aliyuncs.com/ehanghai/shiprouteapi:latest'
    ports:
          - "9002:9002"
    labels:
      aliyun.scale: '1'
      aliyun.routing.port_9002: 'http://shipRouteApi;http://ship.ehanghai.cn'
    restart: always
    memswap_limit: 0
    shm_size: 0
    memswap_reservation: 0
    kernel_memory: 0
    name: shipRouteApi
    hostname: shipRouteApi
