version: '2'
services:
  routeCheckApi:
    image: 'registry.cn-hangzhou.aliyuncs.com/ehanghai/routecheckapi:latest'
    ports:
          - "9003:9003"
    labels:
      aliyun.scale: '1'
      aliyun.routing.port_9003: 'http://routeCheckApi;http://duanwj-route.ehanghai.cn'
    restart: always
    memswap_limit: 0
    shm_size: 0
    memswap_reservation: 0
    kernel_memory: 0
    name: routeCheckApi
    hostname: routeCheckApi