server:
  port: 9003

spring:
    sys-datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://ehanghai-db-app.mysql.rds.aliyuncs.com:3306/app?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: app
      password: app2016
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 300000

    nav-datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://ehanghai-db-ais.mysql.rds.aliyuncs.com:3306/sea_nav?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: sea_nav
      password: sea_nav2016
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 300000


    redis:
            host: r-bp1f488ab09eb2a4345.redis.rds.aliyuncs.com
            port: 6379
            password: xC123456
            pool:
                  max-idle: 100
                  min-idle: 1
                  max-active: 1000
                  max-wait: -1
mapper:
    mappers:
         - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

